/**
 * Message Codes
 *
 * Backend trả về code, frontend tự translate.
 * Thêm domain-specific codes vào section riêng khi mở rộng.
 */
export const MESSAGE_CODES = {
  AUTH: {
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
    REFRESH_SUCCESS: 'AUTH_REFRESH_SUCCESS',
    CHANGE_PASSWORD_SUCCESS: 'AUTH_CHANGE_PASSWORD_SUCCESS',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
    INVALID_CURRENT_PASSWORD: 'AUTH_INVALID_CURRENT_PASSWORD',
    NEW_PASSWORD_SAME_AS_CURRENT: 'AUTH_NEW_PASSWORD_SAME_AS_CURRENT',
    TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
    ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
    FORBIDDEN: 'AUTH_FORBIDDEN',
  },

  USER: {
    CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
    CREATE_FAILED: 'USER_CREATE_FAILED',
    UPDATE_FAILED: 'USER_UPDATE_FAILED',
    FIND_BY_EMAIL_FAILED: 'USER_FIND_BY_EMAIL_FAILED',
    FIND_BY_ID_FAILED: 'USER_FIND_BY_ID_FAILED',
    UPDATE_PASSWORD_FAILED: 'USER_UPDATE_PASSWORD_FAILED',
    CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',
    FIND_PAGINATED_FAILED: 'USER_FIND_PAGINATED_FAILED',
  },

  COMMON: {
    VALIDATION_ERROR: 'COMMON_VALIDATION_ERROR',
    UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
    FORBIDDEN: 'COMMON_FORBIDDEN',
    NOT_FOUND: 'COMMON_NOT_FOUND',
    INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
    BAD_REQUEST: 'COMMON_BAD_REQUEST',
    CONFLICT: 'COMMON_CONFLICT',
    MISSING_TOKEN: 'COMMON_MISSING_TOKEN',
    INVALID_TOKEN: 'COMMON_INVALID_TOKEN',
    VERSION_CONFLICT: 'COMMON_VERSION_CONFLICT',
    FILE_SIZE_EXCEEDS_MAXIMUM_ALLOWED: 'COMMON_FILE_SIZE_EXCEEDS_MAXIMUM_ALLOWED',
    FILE_TYPE_NOT_ALLOWED: 'COMMON_FILE_TYPE_NOT_ALLOWED',
  },
} as const;
